services:
    frontend:
        image: pms-frontend # tag
        container_name: pms-frontend
        ports:
          - 8001:80
        restart: unless-stopped
        depends_on:
          backend:
            condition: service_started

    backend:
        image: pms-backend # tag
        container_name: pms-backend
        environment:
            # optional
            # - DATABASE="pms"

            # mysql ip address
            - HOST=172.30.0.2
            - USER=root

            # should be same as mysql.MYSQL_ROOT_PASSWORD
            - PASSWORD=Abc!@#$%^&*()
            - JWT_SECRET=Xyz)(*&^%$#@!)

            # CORS allowed orgins
            # use "," to split different orgins
            - CORS_ALLOW_ORIGINS=https://pms.tyrantrex.icu,http://test.tyrantrex.icu
        ports:
          - 8000:8080
        restart: unless-stopped
        depends_on:
          mysql:
            condition: service_started

    mysql:
        image: mysql:latest
        environment:
            # should be same as pms.PASSWORD
            - MYSQL_ROOT_PASSWORD=Abc!@#$%^&*()
        ports:
          - 3306:3306
        restart: unless-stopped